apiVersion: pubsub.cnrm.cloud.google.com/v1alpha2
kind: PubSubSubscription
metadata:
  name: echo-read
spec:
  ackDeadlineSeconds: 15
  messageRetentionDuration: 86400s
  retainAckedMessages: false
  topicRef:
    name: echo